import "server-only"

import postgres, { type Sql } from "postgres"

const DATABASE_URL_ENV_KEYS = [
  "DATABASE_URL",
  "POSTGRES_URL",
  "POSTGRES_PRISMA_URL",
  "POSTGRES_URL_NON_POOLING",
] as const

const globalForPostgres = globalThis as typeof globalThis & {
  vellumPostgresClient?: Sql
}

let schemaPromise: Promise<void> | null = null

export function getPostgresDatabaseUrl() {
  for (const key of DATABASE_URL_ENV_KEYS) {
    const value = process.env[key]

    if (value) {
      return value
    }
  }

  return null
}

export function shouldUsePostgresStorage(databasePath?: string) {
  return databasePath === undefined && getPostgresDatabaseUrl() !== null
}

export function getPostgresSql() {
  const databaseUrl = getPostgresDatabaseUrl()

  if (!databaseUrl) {
    throw new Error(
      "DATABASE_URL is required for hosted storage. Connect a Neon Postgres database to this Vercel project."
    )
  }

  globalForPostgres.vellumPostgresClient ??= postgres(databaseUrl, {
    connect_timeout: 10,
    idle_timeout: 20,
    max: 3,
    prepare: false,
  })

  return globalForPostgres.vellumPostgresClient
}

async function createSchema(sql: Sql) {
  await sql.unsafe(`
    CREATE TABLE IF NOT EXISTS transactions (
      sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      id TEXT NOT NULL UNIQUE,
      trade_date TEXT NOT NULL,
      ticker TEXT NOT NULL,
      quantity DOUBLE PRECISION NOT NULL,
      price DOUBLE PRECISION NOT NULL,
      currency TEXT,
      side TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
      account TEXT,
      total_amount DOUBLE PRECISION NOT NULL,
      source_file TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `)

  await sql.unsafe(`
    CREATE INDEX IF NOT EXISTS transactions_trade_date_idx
      ON transactions (trade_date)
  `)

  await sql.unsafe(`
    CREATE INDEX IF NOT EXISTS transactions_account_idx
      ON transactions (account)
  `)

  await sql.unsafe(`
    CREATE INDEX IF NOT EXISTS transactions_ticker_idx
      ON transactions (ticker)
  `)

  await sql.unsafe(`
    CREATE TABLE IF NOT EXISTS saved_trade_writes (
      request_id TEXT PRIMARY KEY,
      payload_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `)

  await sql.unsafe(`
    CREATE TABLE IF NOT EXISTS instrument_exposure_profiles (
      market TEXT NOT NULL,
      ticker TEXT NOT NULL,
      instrument_name TEXT,
      underlying_market TEXT NOT NULL,
      underlying_ticker TEXT NOT NULL,
      exposure_multiplier DOUBLE PRECISION NOT NULL CHECK (exposure_multiplier > 0),
      exposure_direction TEXT NOT NULL CHECK (exposure_direction IN ('long', 'inverse')),
      source TEXT,
      review_status TEXT NOT NULL DEFAULT 'reviewed',
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (market, ticker)
    )
  `)

  await sql.unsafe(`
    CREATE INDEX IF NOT EXISTS instrument_exposure_profiles_underlying_idx
      ON instrument_exposure_profiles (underlying_market, underlying_ticker)
  `)
}

export async function ensurePostgresSchema(sql = getPostgresSql()) {
  schemaPromise ??= createSchema(sql)

  try {
    await schemaPromise
  } catch (error) {
    schemaPromise = null
    throw error
  }
}

export function getLocalSqlitePath(
  databasePath: string | undefined,
  fallback: string
) {
  if (databasePath) {
    return databasePath
  }

  if (process.env.VERCEL) {
    throw new Error(
      "DATABASE_URL is required on Vercel because Function filesystems are not durable. Connect a Neon Postgres database to this project."
    )
  }

  return fallback
}
